apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gogogo
  janus-idp.io/tekton: gogogo
  backstage.io/kubernetes-id: gogogo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gogogo
resources:
- deployment.yaml
- route.yaml
- service.yaml
