apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gogogo 
  janus-idp.io/tekton: gogogo
  backstage.io/kubernetes-id: gogogo
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gogogo
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  